### PR TITLE
add the average identity percentage to the counts

### PR DESCRIPTION
**Pull request by laughedelic**
From the BLAST output we have the `pident` field. We just need to 

1. add this value to the assignment output (this is useful in itself) 
2. calculate the average in the counting step

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes one thing I'm doubting here:
- LCA can be a node that is not among the BLAST hits, so which `pident` should correspond to it in the assignment results? average among all hits for this read?

**Comment by laughedelic** [comment]
Never mind. I forgot that we keep only hits with the same maximum `pindent` 😓

**Comment by eparejatobes** [comment]
In general it should be average across all hits; we're keeping the max so no need to calculate it, but that could be a future setting: something like calculate the LCA for all hits close to the maximum pident, particularly when setting the pident threshold to a lower value.

**Comment by rtobes** [comment]
I agree. And when MG7 evolve for other uses (functional assignment for example) it would be useful.
(the parameter is _pident_ :))

**Comment by laughedelic** [comment]
This is done. With _average_ `pident`:
- in the LCA assignment table per read across all hits
- in the counts table per tax ID

**Pull request merged**
