### PR TITLE
Test with the db.rna16s

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
It appears to be quite inconvenient to have this pipeline code here, because it needs to be included in the fat-jar and introduces private era7-defaults dependency. I'm going to run it here, but then move to the db.rna16s repo.

**Comment by laughedelic** [comment]
Results are in `s3://era7p/mg7-test/data/out/1.0.0-M4-3-g6baecfc/refdb/merge/`

**Comment by marina-manrique** [comment]
Which is the input data of this test?

**Comment by laughedelic** [comment]
@marina-manrique the reference database itself (db.rna16s v0.8.0)

**Comment by eparejatobes** [comment]
what's the status of this?

**Comment by laughedelic** [comment]
@eparejatobes it's done in the db.rna16s repo (see https://github.com/ohnosequences/mg7/pull/77#issuecomment-224445583). This was some intermediate codebase fo the pipeline. I think I will just close this PR.

**Pull request closed without merging**
