### PR TITLE
add Illumina 16S data analysis to tests

### PR DESCRIPTION
**Pull request by eparejatobes**
- [ ] @marina-manrique Description of the samples and mock communities, with links to SRA/BEI/whatever
- [x]  @eparejatobes docs for the mg7 parameters chosen, structure code as much as possible
- [ ] @laughedelic docs for running this, as this is not wholly automated; should go in making-new-releases docs

### CODE REVIEW

**Comment by eparejatobes** [comment]
Already in tests. To-do here:

1. [ ] docs for the dataset we are testing
2. [ ] docs for the parameters chosen
3. [ ] docs for running this, as this is not wholly automated; should go in making-new-releases docs

**Comment by eparejatobes** [comment]
We need to discuss and decide:

1. [ ] How many different Illumina samples we want to run for each and every release
2. [ ] Is it worthwhile at this stage to run any automated tests on the outputs?
3. [ ] Staggered samples: I couldn't find the actual concentration for each taxon. Any ideas where this could be found?

**Comment by eparejatobes** [comment]
Did my part, unassigning myself.

**Comment by eparejatobes** [comment]
@laughedelic @marina-manrique I think I'm opening new issues for what you were to do here, and merging this.

**Comment by eparejatobes** [comment]
#104 and #105. Here we go, LGTM

**Comment by marina-manrique** [comment]
> @marina-manrique the mock communities for PacBio data #102 look to be the same; are they?

No, they are not, here you can see the community ID for each dataset  https://github.com/ohnosequences/mg7/issues/104#issuecomment-240657111

**Pull request merged**
