### PR TITLE
Test data description

### PR DESCRIPTION
**Pull request by marina-manrique**
As discussed in #86.

### CODE REVIEW

**Comment by marina-manrique** [comment]
@eparejatobes please review, don't know if this is what you wanted

**Comment by eparejatobes** [comment]
OK will do. Every time you want me to review something, unassign yourself and assign me please, thanks!

**Comment by marina-manrique** [comment]
> unassign yourself and assign me please, thanks!

done

**Comment by laughedelic** [comment]
What's missing here?

**Comment by eparejatobes** [comment]
Merging.

**Pull request merged**
