### PR TITLE
Assignment to a set of taxas

### PR DESCRIPTION
**Pull request by laughedelic**
This depends on changing the reference databases (not picking the first mapping, but keeping them all)

### CODE REVIEW

**Comment by laughedelic** [comment]
This is done and should work both with single- and multiple-valued DBs 👌

**Comment by laughedelic** [comment]
One question here: now that one BLAST hit may be mapped to several taxas, how do we choose the BBH among these multiple assignments? the first?

**Comment by rtobes** [comment]
The most specific (rank based).
The problem is that the strains, that is the maximum level of specificity, are clasified in the taxonomic tree as _no rank_. In that case you could know that it is an strain if its ancestor is a taxon with _species_ rank.
Then you need to base the specificity on:
-  the rank of the taxon
-  the rank of the closest ancestor

**Comment by laughedelic** [comment]
@rtobes and what if among these taxas, there is no any with these ranks? At the moment there's no any predefined order of ranks in Bio4j/MG7

**Comment by rtobes** [comment]
It is very simple. You can find taxa from any rank in the set of assignments for a RNA sequence.
The order of the ranks is this:
•      1 superkingdom
•	2 kingdom
•	3 superphylum
•	4 phylum
•	5 subphylum
•	6 class
•	7 subclass
•	8 order
•	9 suborder
•	10 family
•	11 subfamily
•	12 tribe
•	13 subtribe
•	14 genus
•	15 subgenus
•	16 species group
•	17 species subgroup
•	18 species
•	19 subspecies
 and _no rank_ can be at any level

**Comment by eparejatobes** [comment]
Why not just take the LCA?

**Comment by laughedelic** [comment]
@rtobes thanks, now it's clear. But I agree with @eparejatobes about LCA, because there may be several specific taxas in the list, which one to choose?

**Comment by rtobes** [comment]
Because I don't trust in the sufficiently specific assignment of all of the taxonomic assignments that each reference sequence has. If we do that, probably, we will diminish the specificity of the assignments for the reference sequences. I agree with taking the LCA but only after an internal refining of the assignments based on consistency,.....
We could do a test for knowing if the rank of the assignments of the reads diminishes a lot using LCA in reference sequences with multiple assignment cases. Adding the values of the order of the rank of each assignment we can have a global value proportional to the specificity of the assignments of the database. In the case of _no rank_ we would have to assign an order_value = [rank of the closest ancestor]+1.

**Comment by laughedelic** [comment]
So I guess, I'm going to implement this ranking.

**Comment by laughedelic** [comment]
This is done. I'm going to merge it soon, but it needs testing, as the assignment code was significantly refactored. We could test it on some of the blast results that we already have.

**Pull request merged**
