### PR TITLE
Remove RNACentralDB dependency

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
Done. See usage in the [test code](https://github.com/ohnosequences/mg7/blob/46545f9eab347d1c7abc1eb5f46ae559f10ba78f/src/test/scala/mg7/pipeline.scala#L21-L25)

**Comment by laughedelic** [comment]
@marina-manrique JFYI, in some recent project with proteins ref-db this was a problem. Now it will be much easier to use 👍 
Although in general I see cases like that as a misuse of MG7 to run only split-blast-merge — we should just have a separate pipeline for it, if it's a frequent need.

**Comment by laughedelic** [comment]
Published under `1.0.0-M4-pr70` version

**Comment by marina-manrique** [comment]
Cool thanks!!

**Pull request merged**
