### PR TITLE
Review preprint sources and see what needs to be updated

### PR DESCRIPTION
**Pull request by eparejatobes**
@marina-manrique @rtobes @laughedelic I have converted the preprint sources to the PeerJ format, and I want to start updating everything. Could you please take a look at the pdf file, and add here what do you think needs to be updated? The pdf is here:

https://github.com/ohnosequences/mg7/blob/2b457b3d0dc06438bcf524dbb8aa00d900ae14c7/docs/mg7-paper/out/paper.pdf

### CODE REVIEW

**Comment by eparejatobes** [comment]
@marina-manrique about the 18S db it is more or less OK, but we don't have any (public) test data for it, right?

**Comment by eparejatobes** [comment]
@rtobes @marina-manrique I have included all your minor edits/comments.

About the figures, we'd then have

1. a generic process description (what is now Figure 1)
2. another for the LCA (what is now Figure 2)
3. a description of the AWS resources/architecture

is that OK?

I have added issues for the rest of your comments: #89 #88 #87 #90

**Comment by marina-manrique** [comment]
And I 'd just add another figure explaining the results of the mock communities. Like bar charts or smth

**Comment by marina-manrique** [comment]
> but we don't have any (public) test data for it, right?

Nope, we don't. I could take a look whether there is a public dataset we could use

**Comment by eparejatobes** [comment]
I added #91 and #92 for figures. LGTM.

**Comment by eparejatobes** [comment]
@rtobes @marina-manrique I think that for all of your comments either there's already an issue for that, or is already included in the paper. If so, let's remove your commented pdfs from the repo.

**Pull request merged**
