### PR TITLE
General stats output

### PR DESCRIPTION
**Pull request by laughedelic**
We need a CSV file of the stats with the following format:

- sample ID
- [ ] total number of input pair-end reads (total number of input pairs)
- [x] number of merged reads
- [ ] number of _not_ merged reads
- [x] number of no-blast-hits
- [ ] number of assigned reads
- [x] number of _not_ assigned reads

### CODE REVIEW

**Comment by laughedelic** [comment]
@marina-manrique I've added an output file with all reads (headers) that didn't get BLAST hits. Do you need only the number or their headers are useful too?

**Comment by laughedelic** [comment]
Things that are counted explicitly:
- total input (paired-end) reads
- number of flash-merged reads
- number of flash-not-merged reads
- number of no-blast-hits reads (+ file with them)
- number of not assigned reads (+ file with them/their IDs)

And I'm adding flash-not-merged reads output files.

**Comment by marina-manrique** [comment]
> Do you need only the number or their headers are useful too?

headers are useful as well

**Comment by laughedelic** [comment]
This seems to be finished. Nothing's tested yet, but let's be optimistic! :tada:

**Pull request merged**
