### PR TITLE
First value in BLAST output does not need to be the one with maximum pident

### PR DESCRIPTION
**Pull request by laughedelic**
It is the one with maximum score.

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes this should solve the problem. I published it as `1.0.0-M5-pr78-123-g2852d94` in case you want to use it right now. I'm going to include more flexible #71 in the next release.

**Comment by eparejatobes** [comment]
See here: https://github.com/ohnosequences/mg7/blob/8f8c8be43b6bfda461517fc8a5a396e61c12c410/src/main/scala/mg7/loquats/3.blast.scala#L54-L62

**Comment by laughedelic** [comment]
What happened? 😮

**Comment by eparejatobes** [comment]
the dangers of web interfaces :stuck_out_tongue:

**Pull request merged**
